# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janelacandidatos.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Candidatos(object):
    def setupUi(self, Candidatos):
        Candidatos.setObjectName("Candidatos")
        Candidatos.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Candidatos)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lw_candidatos = QtWidgets.QListWidget(self.centralwidget)
        self.lw_candidatos.setStyleSheet("font: 75 26pt \"Ubuntu\";")
        self.lw_candidatos.setObjectName("lw_candidatos")
        self.gridLayout.addWidget(self.lw_candidatos, 0, 0, 1, 1)
        Candidatos.setCentralWidget(self.centralwidget)

        self.retranslateUi(Candidatos)
        QtCore.QMetaObject.connectSlotsByName(Candidatos)

    def retranslateUi(self, Candidatos):
        _translate = QtCore.QCoreApplication.translate
        Candidatos.setWindowTitle(_translate("Candidatos", "EMAIL DOS CANDIDATOS"))
